### ISSUE TITLE
Setup the development environment

### ISSUE THREAD

**Issue by carlag-raft** [carlag-raft/raft-exercise#11]
**Description**
Buy, install, setup necessary software, hardware, and tools needed for the development environment.

**Acceptance Criteria**
A working development environment

**Tasks**
- [ ] Install development software and tools
- [ ] Install software and tools for testing
- [ ] Setup dev servers
